version: 2.1

orbs:
  win: circleci/windows@1.0.0

commands:
  build_binary:
    description: 'Build the binary for arch'
    parameters:
      csp_version:
        default: 1.0.8
        type: string
      qjs_version:
        default: 2019-12-21
        type: string
      arch:
        type: string
    steps:
      - checkout
      - run:
          name: 'install deps'
          command: |
            ARCH=<< parameters.arch >> \
              CSP_VERSION=<< parameters.csp_version >> \
              QJS_VERSION=<< parameters.qjs_version >> \
              sh install.sh
      - run:
          name: 'build bin'
          command: |
            ARCH=<< parameters.arch >> sh build.sh
      - persist_to_workspace:
          root: . 
          paths:
            - bin/
       

jobs:
  build_darwin:
    macos:
      xcode: '9.0'
    steps:
      - build_binary:
          arch: 'darwin'
  build_linux:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - build_binary:
          arch: 'linux'
  release:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: /workdir
    steps:
      - attach_workspace:
          at: .
      - run: tree bin

workflows:
  version: 2
  build:
    jobs:
      - build_darwin
      - build_linux
      - release:
          requires:
            - build_darwin
            - build_linux



